In [35]:
import pandas as pd
import requests
import matplotlib.pyplot as plt

url = "https://saddam-teacher-api.onrender.com/supermarket/dirty"
token = "saddam_teacher"
response = requests.get(url,params={'token':token})
data = response.json()
df = pd.DataFrame(data)
df

,branch,category,date,order_id,price,product_name,quantity,total_price,year
0,Chilonzor,Oziq-ovqat,2025-10-02,1,42265.0,Non,10.0,422650,2024
1,Chilonzor,Oziq-ovqat,2025-07-19,2,22343.0,Sut,2.0,44686,2024
2,Sergeli,Ichimlik,2025-08-31,3,15258.0,Yog',1.0,15258,2025
3,Sergeli,Ichimlik,2024-10-16,4,24087.0,Sut,1.0,24087,2025
4,Yunusobod,Oziq-ovqat,2024-04-27,5,9664.0,Shakar,4.0,38656,2024
...,...,...,...,...,...,...,...,...,...
495,Yunusobod,Ichimlik,2025-04-12,496,27460.0,Non,3.0,82380,2025
496,Chilonzor,Oziq-ovqat,2024-05-15,497,30278.0,Yog',8.0,242224,2024
497,Sergeli,Ichimlik,2025-11-25,498,15446.0,Yog',2.0,30892,2025
498,Sergeli,Ichimlik,2024-01-30,499,16879.0,Yog',10.0,168790,2024
499,Yunusobod,Ichimlik,2024-02-17,500,36659.0,Non,8.0,293272,2024

In [33]:
df.isna().sum()

branch          0
category        0
date            0
order_id        0
price           0
product_name    0
quantity        0
total_price     0
year            0
dtype: int64

In [36]:
df['category'] = df['category'].fillna("Qoldiq")
df['price'] = df['price'].fillna(df['price'].median())
df['quantity'] = df['quantity'].fillna(df['quantity'].median())
df

,branch,category,date,order_id,price,product_name,quantity,total_price,year
0,Chilonzor,Oziq-ovqat,2025-10-02,1,42265.0,Non,10.0,422650,2024
1,Chilonzor,Oziq-ovqat,2025-07-19,2,22343.0,Sut,2.0,44686,2024
2,Sergeli,Ichimlik,2025-08-31,3,15258.0,Yog',1.0,15258,2025
3,Sergeli,Ichimlik,2024-10-16,4,24087.0,Sut,1.0,24087,2025
4,Yunusobod,Oziq-ovqat,2024-04-27,5,9664.0,Shakar,4.0,38656,2024
...,...,...,...,...,...,...,...,...,...
495,Yunusobod,Ichimlik,2025-04-12,496,27460.0,Non,3.0,82380,2025
496,Chilonzor,Oziq-ovqat,2024-05-15,497,30278.0,Yog',8.0,242224,2024
497,Sergeli,Ichimlik,2025-11-25,498,15446.0,Yog',2.0,30892,2025
498,Sergeli,Ichimlik,2024-01-30,499,16879.0,Yog',10.0,168790,2024
499,Yunusobod,Ichimlik,2024-02-17,500,36659.0,Non,8.0,293272,2024

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   branch        500 non-null    object
 1   category      500 non-null    object
 2   date          500 non-null    object
 3   order_id      500 non-null    int64
 4   price         500 non-null    float64
 5   product_name  500 non-null    object
 6   quantity      500 non-null    float64
 7   total_price   500 non-null    int64
 8   year          500 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 35.3+ KB

In [37]:
df.to_excel('tayyor_stat.xlsx')